// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuuh5D_dtrwJEz6NxBrn0jYxUe5P3VxEs',
    appId: '1:87640483142:web:982d876935c88bb42a7147',
    messagingSenderId: '87640483142',
    projectId: 'attendanceproject-e62c2',
    authDomain: 'attendanceproject-e62c2.firebaseapp.com',
    storageBucket: 'attendanceproject-e62c2.appspot.com',
    measurementId: 'G-11YVNZ5FV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYs3INIzmmL8AUv5oYV76609bykENUZCU',
    appId: '1:87640483142:android:8827c8dce3694d3f2a7147',
    messagingSenderId: '87640483142',
    projectId: 'attendanceproject-e62c2',
    storageBucket: 'attendanceproject-e62c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEAwiVI03zuzZFMJAWJZcUuI4Wyrc__lw',
    appId: '1:87640483142:ios:127c0d63b0de07452a7147',
    messagingSenderId: '87640483142',
    projectId: 'attendanceproject-e62c2',
    storageBucket: 'attendanceproject-e62c2.appspot.com',
    iosBundleId: 'com.example.attendenceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEAwiVI03zuzZFMJAWJZcUuI4Wyrc__lw',
    appId: '1:87640483142:ios:bf053c6245693e9e2a7147',
    messagingSenderId: '87640483142',
    projectId: 'attendanceproject-e62c2',
    storageBucket: 'attendanceproject-e62c2.appspot.com',
    iosBundleId: 'com.example.attendenceapp.RunnerTests',
  );
}
